-- Demo content for a portfolio deployment. NOT applied by `supabase db
-- reset` (that runs seed.sql) and NOT a migration -- run it by hand, once,
-- against the deployed database:
--
--   psql "$SUPABASE_DB_URL" -v owner_email=you@example.com -f supabase/seed-demo.sql
--
-- (no quotes around the address -- :'owner_email' adds them)
--
-- Everything in here is synthetic. Two drafts of an invented MSA between two
-- invented companies, written to exercise the product rather than to be a
-- contract: the second draft lengthens the term, raises the fee, stretches
-- payment, removes the notices clause, renumbers everything after it, makes
-- termination one-sided, carves the customer out of the liability cap, and
-- adds a data-protection clause that grants perpetual rights. That gives the
-- compare view something to say and the risk delta a genuine before/after.
--
-- The clause text is byte-identical to what ingesting these two drafts would
-- produce -- it was generated by running the real segmenter over them -- so
-- the demo is not showing a shape the pipeline could not produce.
--
-- The analysis rows are written directly rather than produced by a model.
-- That is deliberate: it costs no AI quota, it cannot be broken by a provider
-- outage while somebody is looking at the demo, and it is reproducible. It is
-- also the one thing here that is asserted rather than derived, so treat the
-- findings as illustrative content, not as evidence about the analyser.
--
-- Re-running is safe: the contract is deleted and rebuilt.

\set ON_ERROR_STOP on

-- psql does not substitute :variables inside a dollar-quoted body, so the
-- email is handed to the block through a session setting instead.
select set_config('demo.owner_email', :'owner_email', false);

do $seed$
declare
  v_email text;
  v_user uuid;
  v_org uuid;
  v_contract uuid;
  v_file1 uuid;
  v_file2 uuid;
  v_v1 uuid;
  v_v2 uuid;
  v_a1 uuid;
  v_a2 uuid;
  v_finding uuid;
begin
  v_email := current_setting('demo.owner_email', true);
  select id into v_user from auth.users where email = v_email;
  if v_user is null then
    raise exception 'No user with email %. Create the demo account first, then re-run.', v_email;
  end if;

  -- The account's existing organisation, or a new one if this is a fresh
  -- project. create_organization() is security definer and reads the caller's
  -- JWT, which a psql session does not have, so the rows go in directly.
  select org_id into v_org from public.org_members where user_id = v_user order by created_at asc limit 1;
  if v_org is null then
    insert into public.organizations (name) values ('Demo Legal') returning id into v_org;
    insert into public.org_members (org_id, user_id, role) values (v_org, v_user, 'owner');
  end if;

  delete from public.contracts where org_id = v_org and title = 'Orion Ledger MSA';

  -- Timestamps are staggered on purpose. Everything the intelligence layer
  -- does with an analysis starts from "the newest one per contract", and two
  -- rows inserted in one transaction share now() to the microsecond -- which
  -- made the choice between the original draft and the revision a coin flip.
  insert into public.contracts (org_id, title, status, created_by, created_at, updated_at)
  values (v_org, 'Orion Ledger MSA', 'ready', v_user, now() - interval '10 days', now() - interval '1 day')
  returning id into v_contract;

  -- Storage holds no object for these: the seed writes the parse output, not
  -- the source file. Nothing in the app reads the file back after ingest.
  insert into public.contract_files (contract_id, org_id, storage_path, filename, mime_type, size_bytes, checksum_sha256)
  values (v_contract, v_org, v_org || '/' || v_contract || '/demo-v1.docx', 'Orion_MSA_v1.docx',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 2210,
          extensions.digest('demo-orion-v1', 'sha256'))
  returning id into v_file1;

  insert into public.contract_files (contract_id, org_id, storage_path, filename, mime_type, size_bytes, checksum_sha256)
  values (v_contract, v_org, v_org || '/' || v_contract || '/demo-v2.docx', 'Orion_MSA_v2.docx',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 2338,
          extensions.digest('demo-orion-v2', 'sha256'))
  returning id into v_file2;

  insert into public.contract_versions (contract_id, org_id, file_id, version_no, created_at)
  values (v_contract, v_org, v_file1, 1, now() - interval '10 days') returning id into v_v1;
  insert into public.contract_versions (contract_id, org_id, file_id, version_no, created_at)
  values (v_contract, v_org, v_file2, 2, now() - interval '1 day') returning id into v_v2;

  insert into public.clauses (version_id, org_id, ordinal, clause_number, lang, body) values
    (v_v1, v_org, 1, null, 'en', $q$MASTER SERVICES AGREEMENT
This Master Services Agreement is made between Orion Ledger Technologies W.L.L., a company registered in the State of Kuwait ("the Provider"), and Al Bayan Trading Company K.S.C.C. ("the Customer").
Effective Date: 1 March 2026
Governing Law: Laws of the State of Kuwait$q$),
    (v_v1, v_org, 2, $q$1$q$, 'en', $q$Definitions
In this Agreement, "Services" means the software implementation and support services described in Schedule A, and "Deliverables" means any output produced by the Provider in the course of performing the Services.$q$),
    (v_v1, v_org, 3, $q$2$q$, 'en', $q$Services
The Provider shall perform the Services with reasonable skill and care and in accordance with the service levels set out in Schedule B.$q$),
    (v_v1, v_org, 4, $q$3$q$, 'en', $q$Term
This Agreement commences on the Effective Date and continues for an initial term of twenty-four (24) months, renewing automatically for successive twelve (12) month terms unless either party gives written notice of non-renewal at least sixty (60) days before the end of the then-current term.$q$),
    (v_v1, v_org, 5, $q$4$q$, 'en', $q$Fees
The Customer shall pay the Provider a fee of KWD 12,500 per quarter, payable in advance. No single total contract value is stated in this Agreement.$q$),
    (v_v1, v_org, 6, $q$5$q$, 'en', $q$Payment
Each invoice is payable within thirty (30) days of receipt. Late payments carry interest at one percent (1%) per month.$q$),
    (v_v1, v_org, 7, $q$6$q$, 'en', $q$Confidentiality
Each party shall keep confidential all Confidential Information of the other party and shall not disclose it to any third party without prior written consent, except where disclosure is required by law.$q$),
    (v_v1, v_org, 8, $q$7$q$, 'en', $q$Limitation of Liability
Each party aggregate liability under this Agreement shall not exceed the total fees paid by the Customer in the twelve (12) months preceding the event giving rise to the claim.$q$),
    (v_v1, v_org, 9, $q$8$q$, 'en', $q$Termination
Either party may terminate this Agreement for convenience on sixty (60) days written notice to the other party.$q$),
    (v_v1, v_org, 10, $q$9$q$, 'en', $q$Notices
All notices under this Agreement shall be delivered by courier to the registered address of the receiving party and are deemed received on the second business day after despatch.$q$),
    (v_v1, v_org, 11, $q$10$q$, 'en', $q$Governing Law
This Agreement is governed by the laws of the State of Kuwait, and the parties submit to the exclusive jurisdiction of the courts of Kuwait City.$q$),
    (v_v1, v_org, 12, $q$11$q$, 'ar', $q$Force Majeure
لا يتحمل أي من الطرفين المسؤولية عن أي تأخير أو إخلال ناتج عن ظرف خارج عن سيطرته المعقولة، بشرط إخطار الطرف الآخر خلال خمسة عشر يوماً من وقوع الظرف.$q$);

  insert into public.clauses (version_id, org_id, ordinal, clause_number, lang, body) values
    (v_v2, v_org, 1, null, 'en', $q$MASTER SERVICES AGREEMENT
This Master Services Agreement is made between Orion Ledger Technologies W.L.L., a company registered in the State of Kuwait ("the Provider"), and Al Bayan Trading Company K.S.C.C. ("the Customer").
Effective Date: 1 March 2026
Governing Law: Laws of the State of Kuwait$q$),
    (v_v2, v_org, 2, $q$1$q$, 'en', $q$Definitions
In this Agreement, "Services" means the software implementation and support services described in Schedule A, and "Deliverables" means any output produced by the Provider in the course of performing the Services.$q$),
    (v_v2, v_org, 3, $q$2$q$, 'en', $q$Services
The Provider shall perform the Services with reasonable skill and care and in accordance with the service levels set out in Schedule B.$q$),
    (v_v2, v_org, 4, $q$3$q$, 'en', $q$Term
This Agreement commences on the Effective Date and continues for an initial term of thirty-six (36) months, renewing automatically for successive twelve (12) month terms unless either party gives written notice of non-renewal at least ninety (90) days before the end of the then-current term.$q$),
    (v_v2, v_org, 5, $q$4$q$, 'en', $q$Fees
The Customer shall pay the Provider a fee of KWD 14,750 per quarter, payable in advance. No single total contract value is stated in this Agreement.$q$),
    (v_v2, v_org, 6, $q$5$q$, 'en', $q$Payment
Each invoice is payable within forty-five (45) days of receipt. Late payments carry interest at one percent (1%) per month.$q$),
    (v_v2, v_org, 7, $q$6$q$, 'en', $q$Confidentiality
Each party shall keep confidential all Confidential Information of the other party and shall not disclose it to any third party without prior written consent, except where disclosure is required by law.$q$),
    (v_v2, v_org, 8, $q$7$q$, 'en', $q$Limitation of Liability
Each party aggregate liability under this Agreement shall not exceed the total fees paid by the Customer in the twelve (12) months preceding the event giving rise to the claim, provided that the Customer liability for indemnity claims, breach of confidentiality and infringement of intellectual property rights shall be unlimited.$q$),
    (v_v2, v_org, 9, $q$8$q$, 'en', $q$Termination
The Provider may terminate this Agreement for convenience on thirty (30) days written notice to the Customer. The Customer may terminate only for material breach that remains uncured for ninety (90) days.$q$),
    (v_v2, v_org, 10, $q$9$q$, 'en', $q$Governing Law
This Agreement is governed by the laws of the State of Kuwait, and the parties submit to the exclusive jurisdiction of the courts of Kuwait City.$q$),
    (v_v2, v_org, 11, $q$10$q$, 'ar', $q$Force Majeure
لا يتحمل أي من الطرفين المسؤولية عن أي تأخير أو إخلال ناتج عن ظرف خارج عن سيطرته المعقولة، بشرط إخطار الطرف الآخر خلال خمسة عشر يوماً من وقوع الظرف.$q$),
    (v_v2, v_org, 12, $q$11$q$, 'en', $q$Data Protection
The Customer grants the Provider an irrevocable right to process and retain Customer data after termination for the Provider own product development purposes, without further consent or compensation.$q$);

  insert into public.analyses (org_id, contract_id, version_id, content_hash, status, schema_version, created_at, updated_at, summary, fields, obligations, obligation_parties)
  values (
    v_org, v_contract, v_v1, 'demo-orion-v1', 'ready', 1,
    now() - interval '10 days', now() - interval '10 days',
    'A two-year services agreement between Orion Ledger Technologies and Al Bayan Trading, auto-renewing in twelve-month terms unless either side gives sixty days notice. Fees are KWD 12,500 quarterly in advance, invoices payable within thirty days. Liability is capped for both parties at twelve months of fees. Either party may walk away on sixty days notice. Kuwaiti law and the courts of Kuwait City govern; force majeure is stated in Arabic.',
    jsonb_build_object('parties', jsonb_build_array('Orion Ledger Technologies W.L.L.', 'Al Bayan Trading Company K.S.C.C.'), 'effectiveDate', '1 March 2026', 'termLength', $q$twenty-four (24) months$q$, 'governingLaw', 'Laws of the State of Kuwait', 'totalValue', null),
    jsonb_build_array(
      jsonb_build_object(
        'obligor', $q$either party$q$, 'action', $q$gives written notice of non-renewal$q$, 'due', $q$at least sixty (60) days before the end of the then-current term$q$,
        'partyRole', $q$both$q$, 'clauseId', (select id from public.clauses where version_id = v_v1 and ordinal = 4),
        'dueSpec', jsonb_build_object('anchor', $q$term_end$q$, 'anchorDate', null, 'offset', 60, 'unit', $q$day$q$, 'direction', $q$before$q$, 'verbatim', $q$at least sixty (60) days before the end of the then-current term$q$)
      ),
      jsonb_build_object(
        'obligor', $q$the Customer$q$, 'action', $q$pay the Provider a fee of KWD 12,500 per quarter, payable in advance$q$, 'due', null,
        'partyRole', $q$party_b$q$, 'clauseId', (select id from public.clauses where version_id = v_v1 and ordinal = 5),
        'dueSpec', null
      ),
      jsonb_build_object(
        'obligor', $q$the Customer$q$, 'action', $q$pay each invoice$q$, 'due', $q$within thirty (30) days of receipt$q$,
        'partyRole', $q$party_b$q$, 'clauseId', (select id from public.clauses where version_id = v_v1 and ordinal = 6),
        'dueSpec', jsonb_build_object('anchor', $q$contract_event$q$, 'anchorDate', null, 'offset', 30, 'unit', $q$day$q$, 'direction', $q$after$q$, 'verbatim', $q$within thirty (30) days of receipt$q$)
      ),
      jsonb_build_object(
        'obligor', $q$either party$q$, 'action', $q$give written notice to terminate for convenience$q$, 'due', $q$sixty (60) days written notice$q$,
        'partyRole', $q$both$q$, 'clauseId', (select id from public.clauses where version_id = v_v1 and ordinal = 9),
        'dueSpec', jsonb_build_object('anchor', $q$contract_event$q$, 'anchorDate', null, 'offset', 60, 'unit', $q$day$q$, 'direction', $q$before$q$, 'verbatim', $q$sixty (60) days written notice$q$)
      )
    ),
    jsonb_build_array('Orion Ledger Technologies W.L.L.', 'Al Bayan Trading Company K.S.C.C.')
  ) returning id into v_a1;

  insert into public.risk_findings (analysis_id, org_id, clause_id, rule_key, kind, severity, title, reason, reason_ar)
  values (v_a1, v_org, null, $q$termination_clause$q$, $q$playbook$q$, 'high', $q$No termination for cause$q$, $q$The contract allows termination for convenience but says nothing about terminating for material breach or default, leaving no stated remedy when the other side fails to perform.$q$, $q$يسمح العقد بالإنهاء لدواعي الملاءمة لكنه لا ينص على الإنهاء بسبب الإخلال الجوهري، فلا يوجد علاج منصوص عليه عند تقصير الطرف الآخر.$q$)
  returning id into v_finding;

  insert into public.risk_findings (analysis_id, org_id, clause_id, rule_key, kind, severity, title, reason, reason_ar)
  values (v_a1, v_org, null, $q$dispute_resolution$q$, $q$playbook$q$, 'low', $q$No escalation before litigation$q$, $q$The contract names a court but does not require negotiation or mediation first, so any disagreement goes straight to litigation.$q$, $q$يحدد العقد محكمة مختصة لكنه لا يشترط التفاوض أو الوساطة أولاً، فينتقل أي خلاف مباشرة إلى التقاضي.$q$)
  returning id into v_finding;

  insert into public.analyses (org_id, contract_id, version_id, content_hash, status, schema_version, created_at, updated_at, summary, fields, obligations, obligation_parties)
  values (
    v_org, v_contract, v_v2, 'demo-orion-v2', 'ready', 1,
    now() - interval '1 day', now() - interval '1 day',
    'The returned draft of the Orion Ledger agreement. The term is now three years with ninety days notice to stop renewal, the quarterly fee rises to KWD 14,750 and payment stretches to forty-five days. Termination is no longer mutual: the Provider may leave for convenience on thirty days notice while the Customer must prove an uncured material breach. The liability cap now excludes the Customer for indemnity, confidentiality and IP claims, and a new clause grants the Provider perpetual rights over Customer data after termination. The notices clause has been removed.',
    jsonb_build_object('parties', jsonb_build_array('Orion Ledger Technologies W.L.L.', 'Al Bayan Trading Company K.S.C.C.'), 'effectiveDate', '1 March 2026', 'termLength', $q$thirty-six (36) months$q$, 'governingLaw', 'Laws of the State of Kuwait', 'totalValue', null),
    jsonb_build_array(
      jsonb_build_object(
        'obligor', $q$either party$q$, 'action', $q$gives written notice of non-renewal$q$, 'due', $q$at least ninety (90) days before the end of the then-current term$q$,
        'partyRole', $q$both$q$, 'clauseId', (select id from public.clauses where version_id = v_v2 and ordinal = 4),
        'dueSpec', jsonb_build_object('anchor', $q$term_end$q$, 'anchorDate', null, 'offset', 90, 'unit', $q$day$q$, 'direction', $q$before$q$, 'verbatim', $q$at least ninety (90) days before the end of the then-current term$q$)
      ),
      jsonb_build_object(
        'obligor', $q$the Customer$q$, 'action', $q$pay the Provider a fee of KWD 14,750 per quarter, payable in advance$q$, 'due', null,
        'partyRole', $q$party_b$q$, 'clauseId', (select id from public.clauses where version_id = v_v2 and ordinal = 5),
        'dueSpec', null
      ),
      jsonb_build_object(
        'obligor', $q$the Customer$q$, 'action', $q$pay each invoice$q$, 'due', $q$within forty-five (45) days of receipt$q$,
        'partyRole', $q$party_b$q$, 'clauseId', (select id from public.clauses where version_id = v_v2 and ordinal = 6),
        'dueSpec', jsonb_build_object('anchor', $q$contract_event$q$, 'anchorDate', null, 'offset', 45, 'unit', $q$day$q$, 'direction', $q$after$q$, 'verbatim', $q$within forty-five (45) days of receipt$q$)
      ),
      jsonb_build_object(
        'obligor', $q$the Provider$q$, 'action', $q$give written notice to terminate for convenience$q$, 'due', $q$thirty (30) days written notice$q$,
        'partyRole', $q$party_a$q$, 'clauseId', (select id from public.clauses where version_id = v_v2 and ordinal = 9),
        'dueSpec', jsonb_build_object('anchor', $q$contract_event$q$, 'anchorDate', null, 'offset', 30, 'unit', $q$day$q$, 'direction', $q$before$q$, 'verbatim', $q$thirty (30) days written notice$q$)
      )
    ),
    jsonb_build_array('Orion Ledger Technologies W.L.L.', 'Al Bayan Trading Company K.S.C.C.')
  ) returning id into v_a2;

  insert into public.risk_findings (analysis_id, org_id, clause_id, rule_key, kind, severity, title, reason, reason_ar)
  values (v_a2, v_org, (select id from public.clauses where version_id = v_v2 and ordinal = 9), $q$termination_clause$q$, $q$asymmetry$q$, 'high', $q$Termination rights are one-sided$q$, $q$The Provider may terminate for convenience on thirty days notice; the Customer may terminate only for an uncured material breach after ninety days.$q$, $q$يجوز للمزوّد الإنهاء لدواعي الملاءمة بإشعار ثلاثين يوماً، بينما لا يجوز للعميل الإنهاء إلا لإخلال جوهري لم يُعالَج خلال تسعين يوماً.$q$)
  returning id into v_finding;
  insert into public.finding_evidence (finding_id, org_id, clause_id, quote, ordinal)
  values (v_finding, v_org, (select id from public.clauses where version_id = v_v2 and ordinal = 9), $q$The Provider may terminate this Agreement for convenience on thirty (30) days written notice to the Customer.$q$, 0);

  insert into public.risk_findings (analysis_id, org_id, clause_id, rule_key, kind, severity, title, reason, reason_ar)
  values (v_a2, v_org, (select id from public.clauses where version_id = v_v2 and ordinal = 8), $q$liability_cap$q$, $q$playbook$q$, 'high', $q$Customer liability is uncapped for key claims$q$, $q$The cap applies to both parties, then carves the Customer out of it for indemnity, confidentiality and IP claims -- the categories most likely to produce a large claim.$q$, $q$يسري سقف المسؤولية على الطرفين ثم يستثني العميل منه في مطالبات التعويض والسرية والملكية الفكرية، وهي أكثر الفئات احتمالاً لمطالبة كبيرة.$q$)
  returning id into v_finding;
  insert into public.finding_evidence (finding_id, org_id, clause_id, quote, ordinal)
  values (v_finding, v_org, (select id from public.clauses where version_id = v_v2 and ordinal = 8), $q$the Customer liability for indemnity claims, breach of confidentiality and infringement of intellectual property rights shall be unlimited$q$, 0);

  insert into public.risk_findings (analysis_id, org_id, clause_id, rule_key, kind, severity, title, reason, reason_ar)
  values (v_a2, v_org, (select id from public.clauses where version_id = v_v2 and ordinal = 12), $q$data_protection$q$, $q$playbook$q$, 'high', $q$Irrevocable data rights survive termination$q$, $q$The Provider keeps the right to process and retain Customer data after the contract ends, for its own product development, with no further consent and no deletion obligation.$q$, $q$يحتفظ المزوّد بحق معالجة بيانات العميل والاحتفاظ بها بعد انتهاء العقد لأغراض تطوير منتجاته، دون موافقة إضافية ودون التزام بالحذف.$q$)
  returning id into v_finding;
  insert into public.finding_evidence (finding_id, org_id, clause_id, quote, ordinal)
  values (v_finding, v_org, (select id from public.clauses where version_id = v_v2 and ordinal = 12), $q$an irrevocable right to process and retain Customer data after termination$q$, 0);

  raise notice 'Seeded contract % with 2 versions under org %', v_contract, v_org;
end
$seed$;
